//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1525591_CO5027
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_1525591_co5027_aziimEntities1 : DbContext
    {
        public db_1525591_co5027_aziimEntities1()
            : base("name=db_1525591_co5027_aziimEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<watchCart> watchCarts { get; set; }
        public virtual DbSet<watchProdType> watchProdTypes { get; set; }
        public virtual DbSet<watchProduct> watchProducts { get; set; }
    }
}
