//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1525591_CO5027
{
    using System;
    using System.Collections.Generic;
    
    public partial class watchCart
    {
        public int ID { get; set; }
        public string watchCustID { get; set; }
        public int watchProID { get; set; }
        public int watchAmount { get; set; }
        public Nullable<System.DateTime> watchDateBuy { get; set; }
        public bool watchIsInCart { get; set; }
    
        public virtual watchProdType watchProdType { get; set; }
    }
}
